### PR TITLE
Add KiwiTokenizer for Korean Tokenizing

### PR DESCRIPTION
**Pull request by Kesta-bos**
When tokenizing Korean, the Kiwi tokenizer is more accurate than Spacy's Korean model, and is superior in terms of resources and speed.

### CODE REVIEW

**Comment by vsabolcec** [comment]
Hi! Thank you for your contribution

I tested your code and it uses more RAM (0.8GB vs 1.2GB) and takes longer to execute (0.8s vs 22.9s) than the existing implementation. Do you have any benchmarks comparing Spacy and Kiwi tokenizer?

**Comment by Kesta-bos** [comment]
Morphological analysis of Korean text is particularly complex compared to other languages like English or Chinese due to unique linguistic characteristics. The main factors making Korean morphological analysis challenging include:

1. **Agglutinative Structure**: Multiple morphemes attach to a root to form words, each indicating different meanings and grammatical functions.

2. **Changing Verb Endings**: Korean verb endings vary according to tense, politeness levels, and discourse, resulting in numerous possibilities for a single verb.

3. **Irregular Spacing**: Irregular spacing between words makes it difficult to determine the boundaries of morphemes.

4. **Ambiguity and Homophony**: The abundance of homophones and words with multiple meanings requires precise interpretation according to context.

5. **Hanja and Loanwords**: The use of Sino-Korean characters and foreign loanwords increases the complexity of morpheme analysis.

Natural language processing (NLP) in Korean essentially requires tokenization based on the 'Standard Part-of-Speech Tag System' of the National Institute of Korean Language due to the aforementioned characteristics. However, as SpaCy uses a model trained on a basic tag list, it poses obstacles in tasks like stopwords extraction and statistical analysis.

For example, when tokenizing the sentence '제 차에있는 차는 차가운 무슨 차일까요?' (What is the tea in my car that is cold?), the Kiwi tokenizer parses it as follows: [('저', 'N'), ('의', 'J'), ('차', 'N'), ('에', 'J'), ('있', 'VV'), ('는', 'E'), ('차', 'N'), ('는', 'J'), ('차갑', 'VA'), ('은', 'E'), ('무슨', 'M'), ('차', 'N'), ('이', 'VC'), ('ᆯ까요', 'E'), ('?', 'S')]. In contrast, SpaCy analyzes it as: [('제', 'MMD'), ('차에있', 'NCN'), ('는', 'JCA'), ('차', 'NCN'), ('는', 'JCS'), ('차갑', 'PAA'), ('ㄴ', 'ETM'), ('무슨', 'MMD'), ('차일까요', 'NCPA'), ('?', 'SF')]. This demonstrates that SpaCy doesn't adequately recognize detailed morpheme tags necessary for Korean analysis, hinting at limitations in analyzing grammatical functions and meanings that are crucial in actual language use.

Therefore, despite potential performance losses, Korean tokenizers should use a separate library (Kiwi) instead of SpaCy. Kiwi is also the highest-performing Korean tokenizer among those that can be integrated into datatrove, as evidenced by benchmarks (https://github.com/bab2min/kiwipiepy/tree/main/benchmark/disambiguate) and also boasts impressive processing speeds (https://lab.bab2min.pe.kr/kiwi).

**Reference benchmarks:**
Probably, the tokenizer currently set in datatrove is based on mecab, which is very inaccurate, so we tested it against the smallest model(sm) trained in Spacy.
The results of a single-process run on the first 10,000 samples from the wikipedia-ko dataset are as follows (https://pastebin.com/AnV0nLFP):
SpaCy Tokenization took 551.16 seconds and used 689.57 MB for the first 10,000 texts.
Kiwi Tokenization took 1886.06 seconds and used 201.93 MB for the first 10,000 texts.

**Comment by Kesta-bos** [comment]
> Morphological analysis of Korean text is particularly complex compared to other languages like English or Chinese due to unique linguistic characteristics. The main factors making Korean morphological analysis challenging include:
> 
> 1. **Agglutinative Structure**: Multiple morphemes attach to a root to form words, each indicating different meanings and grammatical functions.
> 2. **Changing Verb Endings**: Korean verb endings vary according to tense, politeness levels, and discourse, resulting in numerous possibilities for a single verb.
> 3. **Irregular Spacing**: Irregular spacing between words makes it difficult to determine the boundaries of morphemes.
> 4. **Ambiguity and Homophony**: The abundance of homophones and words with multiple meanings requires precise interpretation according to context.
> 5. **Hanja and Loanwords**: The use of Sino-Korean characters and foreign loanwords increases the complexity of morpheme analysis.
> 
> Natural language processing (NLP) in Korean essentially requires tokenization based on the 'Standard Part-of-Speech Tag System' of the National Institute of Korean Language due to the aforementioned characteristics. However, as SpaCy uses a model trained on a basic tag list, it poses obstacles in tasks like stopwords extraction and statistical analysis.
> 
> For example, when tokenizing the sentence '제 차에있는 차는 차가운 무슨 차일까요?' (What is the tea in my car that is cold?), the Kiwi tokenizer parses it as follows: [('저', 'N'), ('의', 'J'), ('차', 'N'), ('에', 'J'), ('있', 'VV'), ('는', 'E'), ('차', 'N'), ('는', 'J'), ('차갑', 'VA'), ('은', 'E'), ('무슨', 'M'), ('차', 'N'), ('이', 'VC'), ('ᆯ까요', 'E'), ('?', 'S')]. In contrast, SpaCy analyzes it as: [('제', 'MMD'), ('차에있', 'NCN'), ('는', 'JCA'), ('차', 'NCN'), ('는', 'JCS'), ('차갑', 'PAA'), ('ㄴ', 'ETM'), ('무슨', 'MMD'), ('차일까요', 'NCPA'), ('?', 'SF')]. This demonstrates that SpaCy doesn't adequately recognize detailed morpheme tags necessary for Korean analysis, hinting at limitations in analyzing grammatical functions and meanings that are crucial in actual language use.
> 
> Therefore, despite potential performance losses, Korean tokenizers should use a separate library (Kiwi) instead of SpaCy. Kiwi is also the highest-performing Korean tokenizer among those that can be integrated into datatrove, as evidenced by benchmarks (https://github.com/bab2min/kiwipiepy/tree/main/benchmark/disambiguate) and also boasts impressive processing speeds (https://lab.bab2min.pe.kr/kiwi).
> 
> **Reference benchmarks:** Probably, the tokenizer currently set in datatrove is based on mecab, which is very inaccurate, so we tested it against the smallest model(sm) trained in Spacy. The results of a single-process run on the first 10,000 samples from the wikipedia-ko dataset are as follows (https://pastebin.com/AnV0nLFP): SpaCy Tokenization took 551.16 seconds and used 689.57 MB for the first 10,000 texts. Kiwi Tokenization took 1886.06 seconds and used 201.93 MB for the first 10,000 texts.

Also, can you provide a non-english filtered bucket for further multilingual tokenization analysis? If I filter again through datatrove in commoncrawl, it would be resource intensive by trafilatura.

**Comment by Kesta-bos** [comment]
When comparing a filter created with KiwiTokenizer and a stopword filter created with SpacyTokenizer, Kiwi tokenized correctly, but Spacy tokenized incorrectly, resulting in stopwords for nouns and strange words.

### KiwiTokenizer's Filter
max_avg_word_length: 3
max_non_alpha_words_ratio: 0.7
min_avg_word_length: 0
stopwords:
- "하"
- "의"
- "이"
- "다"
- "는"
- "었"
- "ᆫ"
- "에"
- "년"
- "을"
- "어"
- "은"
- "되"
- "를"
- "고"
- "에서"
- "있"
- "가"
- "으로"

### SpacyTokenizer's Filter
max_avg_word_length: 5
max_non_alpha_words_ratio: 0.8
min_avg_word_length: 2
stopwords:
- "있다"
- "《"
- "》"
- "이"
- "역"
- "는"
- "수"
- "선수" (Player)
- "영화" (Movie)
- "은"
- "축구" (Soccer)
- "있는"
- "%xB7"
- "그"
- "대한민국의" (of Korea)
- "의"
- "외부" (External)
- "링크" (Link)
- "및"
- "각주" (Footnotes)
- "한"

**Comment by vsabolcec** [comment]
Thank you. I will merge the pull request.

**Comment by Kesta-bos** [comment]
By any chance, is there currently a commoncrawl dataset bucket filtered non-english?

**Pull request merged**
